### ISSUE TITLE
The link to the private channel seems broken

### ISSUE THREAD

**Issue by drwahl** [computmaxer/roku-hdhomerun#7]
It looks like maybe Roku updated something on their side to make the link to the private channel break.  Halp?

**Comment by computmaxer** [comment]
I haven't done anything with this for more than 2 years, are you still using it?

**Comment by drwahl** [comment]
I'm trying to stream my hdhr prime to my roku. I only do this during football season, so I also haven't used this in almost a year, but I believe it was working back then.  I have wallop running, but I without this roku channel, I'm not sure how to get the stream from wallop onto the roku.

**Comment by drwahl** [comment]
It appears that the new process to add a private channel requires the channel creator to share the channel "code".  I assume you can find the code in your roku developer account.

**Comment by computmaxer** [comment]
@drwahl there's a "Vanity access code" of `A3XYN`. Is that what you need?

**Comment by drwahl** [comment]
That's **exactly** what I needed! Thank you!
